// <auto-generated />
using BullFins.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BullFins.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190407161528_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BullFins.Models.EF_Models+Company", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("date");

                    b.Property<string>("iexId");

                    b.Property<bool>("isEnabled");

                    b.Property<string>("name");

                    b.Property<string>("type");

                    b.HasKey("symbol");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BullFins.Models.EF_Models+Financials", b =>
                {
                    b.Property<string>("reportdate")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SymbolFinancialsymbol");

                    b.Property<decimal>("cashflow");

                    b.Property<decimal>("grossprofit");

                    b.Property<decimal>("totalassets");

                    b.Property<decimal>("totalcash");

                    b.Property<decimal>("totalliabilities");

                    b.Property<decimal>("totalrevenue");

                    b.HasKey("reportdate");

                    b.HasIndex("SymbolFinancialsymbol");

                    b.ToTable("Financials");
                });

            modelBuilder.Entity("BullFins.Models.EF_Models+StockStats", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("cash");

                    b.Property<decimal>("debt");

                    b.Property<decimal>("dividendRate");

                    b.Property<decimal>("grossProfit");

                    b.Property<decimal>("revenue");

                    b.Property<decimal>("revenuePerShare");

                    b.HasKey("symbol");

                    b.ToTable("StockStatistics");
                });

            modelBuilder.Entity("BullFins.Models.EF_Models+SymbolFinancial", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.HasKey("symbol");

                    b.ToTable("SymbolFinancials");
                });

            modelBuilder.Entity("BullFins.Models.EF_Models+Financials", b =>
                {
                    b.HasOne("BullFins.Models.EF_Models+SymbolFinancial")
                        .WithMany("financials")
                        .HasForeignKey("SymbolFinancialsymbol");
                });
#pragma warning restore 612, 618
        }
    }
}
